# Generated by Django 6.0 on 2026-01-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizacja', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budzet',
            options={'managed': False, 'verbose_name': 'Budżet', 'verbose_name_plural': 'Budżety'},
        ),
        migrations.AlterModelOptions(
            name='certyfikat',
            options={'managed': False, 'verbose_name': 'Certyfikat', 'verbose_name_plural': 'Certyfikaty'},
        ),
        migrations.AlterModelOptions(
            name='czlonek',
            options={'managed': False, 'verbose_name': 'Członek', 'verbose_name_plural': 'Członkowie'},
        ),
        migrations.AlterModelOptions(
            name='czlonekkierunek',
            options={'managed': False, 'verbose_name': 'Członek Kierunku', 'verbose_name_plural': 'Członkowie Kierunków'},
        ),
        migrations.AlterModelOptions(
            name='czlonekprojektu',
            options={'managed': False, 'verbose_name': 'Członek Projektu', 'verbose_name_plural': 'Członkowie Projektów'},
        ),
        migrations.AlterModelOptions(
            name='czloneksekcji',
            options={'managed': False, 'verbose_name': 'Członek Sekcji', 'verbose_name_plural': 'Członkowie Sekcji'},
        ),
        migrations.AlterModelOptions(
            name='kierunek',
            options={'managed': False, 'verbose_name': 'Kierunek', 'verbose_name_plural': 'Kierunki'},
        ),
        migrations.AlterModelOptions(
            name='odpowiedzislownik',
            options={'managed': False, 'verbose_name': 'Odpowiedź Słownik', 'verbose_name_plural': 'Odpowiedzi Słownik'},
        ),
        migrations.AlterModelOptions(
            name='organizacja',
            options={'managed': False, 'verbose_name': 'Organizacja', 'verbose_name_plural': 'Organizacje'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'managed': False, 'verbose_name': 'Partner', 'verbose_name_plural': 'Partnerzy'},
        ),
        migrations.AlterModelOptions(
            name='projekt',
            options={'managed': False, 'verbose_name': 'Projekt', 'verbose_name_plural': 'Projekty'},
        ),
        migrations.AlterModelOptions(
            name='przychod',
            options={'managed': False, 'verbose_name': 'Przychód', 'verbose_name_plural': 'Przychody'},
        ),
        migrations.AlterModelOptions(
            name='sekcja',
            options={'managed': False, 'verbose_name': 'Sekcja', 'verbose_name_plural': 'Sekcje'},
        ),
        migrations.AlterModelOptions(
            name='spotkanie',
            options={'managed': False, 'verbose_name': 'Spotkanie', 'verbose_name_plural': 'Spotkania'},
        ),
        migrations.AlterModelOptions(
            name='spotkanieczlonek',
            options={'managed': False, 'verbose_name': 'Spotkanie Członek', 'verbose_name_plural': 'Spotkania Członkowie'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'managed': False, 'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownikorganizacja',
            options={'managed': False, 'verbose_name': 'Użytkownik Organizacja', 'verbose_name_plural': 'Użytkownicy Organizacje'},
        ),
        migrations.AlterModelOptions(
            name='widokbazyczlonkow',
            options={'managed': False, 'verbose_name': 'Widok Bazy Członków', 'verbose_name_plural': 'Widoki Bazy Członków'},
        ),
        migrations.AlterModelOptions(
            name='widokbudzetu',
            options={'managed': False, 'verbose_name': 'Widok Budżetu', 'verbose_name_plural': 'Widoki Budżetu'},
        ),
        migrations.AlterModelOptions(
            name='widokcertyfikatow',
            options={'managed': False, 'verbose_name': 'Widok Certyfikatów', 'verbose_name_plural': 'Widoki Certyfikatów'},
        ),
        migrations.AlterModelOptions(
            name='widokobecnosci',
            options={'managed': False, 'verbose_name': 'Widok Obecności', 'verbose_name_plural': 'Widoki Obecności'},
        ),
        migrations.AlterModelOptions(
            name='widokpartnerow',
            options={'managed': False, 'verbose_name': 'Widok Partnerów', 'verbose_name_plural': 'Widoki Partnerów'},
        ),
        migrations.AlterModelOptions(
            name='wydatek',
            options={'managed': False, 'verbose_name': 'Wydatek', 'verbose_name_plural': 'Wydatki'},
        ),
    ]
